// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EInfrastructure.Core.CustomConfiguration.MySql.Migrations
{
    [DbContext(typeof(CustomerConfigurationDbContext))]
    partial class CustomerConfigurationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EInfrastructure.Core.CustomConfiguration.Core.Domain.AppNamespaces", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasMaxLength(36);

                    b.Property<DateTime>("AddTime")
                        .HasColumnName("add_time");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnName("appid")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DelTime")
                        .HasColumnName("del_time");

                    b.Property<DateTime>("EditTime")
                        .HasColumnName("edit_time");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnName("format")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDel")
                        .HasColumnName("is_del");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("app.namespaces");
                });

            modelBuilder.Entity("EInfrastructure.Core.CustomConfiguration.Core.Domain.Apps", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasMaxLength(36);

                    b.Property<DateTime>("AddTime")
                        .HasColumnName("add_time");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnName("appid")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DelTime")
                        .HasColumnName("del_time");

                    b.Property<DateTime>("EditTime")
                        .HasColumnName("edit_time");

                    b.Property<bool>("IsDel")
                        .HasColumnName("is_del");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("apps");
                });

            modelBuilder.Entity("EInfrastructure.Core.CustomConfiguration.Core.Domain.NamespaceItems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasMaxLength(36);

                    b.Property<DateTime>("AddTime")
                        .HasColumnName("add_time");

                    b.Property<long>("AppNamespaceId")
                        .HasColumnName("app_namespace_id")
                        .HasMaxLength(36);

                    b.Property<long?>("AppNamespacesId1");

                    b.Property<DateTime?>("DelTime")
                        .HasColumnName("del_time");

                    b.Property<DateTime>("EditTime")
                        .HasColumnName("edit_time");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnName("environment_name")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDel")
                        .HasColumnName("is_del");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnName("key")
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasMaxLength(200);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AppNamespaceId");

                    b.HasIndex("AppNamespacesId1");

                    b.ToTable("namespace.items");
                });

            modelBuilder.Entity("EInfrastructure.Core.CustomConfiguration.Core.Domain.NamespaceItems", b =>
                {
                    b.HasOne("EInfrastructure.Core.CustomConfiguration.Core.Domain.AppNamespaces")
                        .WithMany("NamespaceItems")
                        .HasForeignKey("AppNamespaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EInfrastructure.Core.CustomConfiguration.Core.Domain.AppNamespaces", "AppNamespaces")
                        .WithMany()
                        .HasForeignKey("AppNamespacesId1");
                });
#pragma warning restore 612, 618
        }
    }
}
