name: Package Push Nuget
on:
  push:
    tags:
    - '*' 

jobs:
  packeg-build:
    name: packeg build and push
    runs-on: ubuntu-latest
    steps:
    
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: version
      run: echo ${{ steps.get_version.outputs.VERSION }}
      
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Pack
      run: dotnet pack --configuration Release -p:IncludeSymbols=true /p:Version=${{ steps.get_version.outputs.VERSION }} --output nupkgs

    - name: Push to Nuget nupkg
      run: |
        cd nupkgs
        dotnet nuget push *.nupkg -k ${{ secrets.GITHUBSECRET }}  -s https://nuget.pkg.github.com/wolfoftotem/index.json
        dotnet nuget push *.snupkg -k ${{ secrets.GITHUBSECRET }}  -s https://nuget.pkg.github.com/wolfoftotem/index.json
        dotnet nuget push *.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push *.snupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
        
